version: '3.6'

services:
  bddmysql:
    container_name: "jee_inj"
    image: mysql:5
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa
    volumes:
      - ./mysqld:/var/lib/mysqld