version: '3.6'

services:
  serveur:
    container_name: "node_sql_injection"
    build:
      context: .
      dockerfile: ./serveur/DockerfileNode

  bddmysql:
    container_name: "jee_inj"
    build:
      context: .
      dockerfile: ./bdd/DockerfileSql
    environment:
      - MYSQL_ROOT_PASSWORD=pa

  proxy:
    container_name: "proxy_sql_injection"
    build:
      context: .
      dockerfile: ./nginx/DockerfileNginx
    restart: always
    ports:
      - 80:80
