version: '3.6'

services:
  bddmysql:
    container_name: "bdbJee"
    image: mysql:5
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa
    volumes:
      - ./mysql:/var/lib/mysqld